# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=LOLPXWSNVREP56CP
sasl.password=tvGdB0W34D172qxpI6+pSP7F83cIgvlDvVYS+x0xfCau/YNtbql4iWBBBdRTbcmT

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-nodejs-client-a37ea0a4-513a-44ee-9ac9-20551022e7fa
